lib: [
  "_build/install/default/lib/banana/META"
  "_build/install/default/lib/banana/basics/basics.a" {"basics/basics.a"}
  "_build/install/default/lib/banana/basics/basics.cma" {"basics/basics.cma"}
  "_build/install/default/lib/banana/basics/basics.cmi" {"basics/basics.cmi"}
  "_build/install/default/lib/banana/basics/basics.cmt" {"basics/basics.cmt"}
  "_build/install/default/lib/banana/basics/basics.cmx" {"basics/basics.cmx"}
  "_build/install/default/lib/banana/basics/basics.cmxa" {"basics/basics.cmxa"}
  "_build/install/default/lib/banana/basics/basics.ml" {"basics/basics.ml"}
  "_build/install/default/lib/banana/basics/basics__Dynamic_array.cmi" {"basics/basics__Dynamic_array.cmi"}
  "_build/install/default/lib/banana/basics/basics__Dynamic_array.cmti" {"basics/basics__Dynamic_array.cmti"}
  "_build/install/default/lib/banana/basics/basics__Flow_graph.cmi" {"basics/basics__Flow_graph.cmi"}
  "_build/install/default/lib/banana/basics/basics__Flow_graph.cmti" {"basics/basics__Flow_graph.cmti"}
  "_build/install/default/lib/banana/basics/basics__Linked_array.cmi" {"basics/basics__Linked_array.cmi"}
  "_build/install/default/lib/banana/basics/basics__Linked_array.cmti" {"basics/basics__Linked_array.cmti"}
  "_build/install/default/lib/banana/basics/dynamic_array.mli" {"basics/dynamic_array.mli"}
  "_build/install/default/lib/banana/basics/flow_graph.mli" {"basics/flow_graph.mli"}
  "_build/install/default/lib/banana/basics/linked_array.mli" {"basics/linked_array.mli"}
  "_build/install/default/lib/banana/dune-package"
  "_build/install/default/lib/banana/opam"
]
libexec: [
  "_build/install/default/lib/banana/basics/basics.cmxs" {"basics/basics.cmxs"}
]
bin: [
  "_build/install/default/bin/main"
]
