lib: [
  "_build/install/default/lib/banana/META"
  "_build/install/default/lib/banana/basics/basics.a" {"basics/basics.a"}
  "_build/install/default/lib/banana/basics/basics.cma" {"basics/basics.cma"}
  "_build/install/default/lib/banana/basics/basics.cmi" {"basics/basics.cmi"}
  "_build/install/default/lib/banana/basics/basics.cmt" {"basics/basics.cmt"}
  "_build/install/default/lib/banana/basics/basics.cmx" {"basics/basics.cmx"}
  "_build/install/default/lib/banana/basics/basics.cmxa" {"basics/basics.cmxa"}
  "_build/install/default/lib/banana/basics/basics.ml" {"basics/basics.ml"}
  "_build/install/default/lib/banana/basics/basics__Display.cmi" {"basics/basics__Display.cmi"}
  "_build/install/default/lib/banana/basics/basics__Display.cmt" {"basics/basics__Display.cmt"}
  "_build/install/default/lib/banana/basics/basics__Display.cmx" {"basics/basics__Display.cmx"}
  "_build/install/default/lib/banana/basics/basics__Dynamic_array.cmi" {"basics/basics__Dynamic_array.cmi"}
  "_build/install/default/lib/banana/basics/basics__Dynamic_array.cmt" {"basics/basics__Dynamic_array.cmt"}
  "_build/install/default/lib/banana/basics/basics__Dynamic_array.cmti" {"basics/basics__Dynamic_array.cmti"}
  "_build/install/default/lib/banana/basics/basics__Dynamic_array.cmx" {"basics/basics__Dynamic_array.cmx"}
  "_build/install/default/lib/banana/basics/basics__Flow_graph.cmi" {"basics/basics__Flow_graph.cmi"}
  "_build/install/default/lib/banana/basics/basics__Flow_graph.cmt" {"basics/basics__Flow_graph.cmt"}
  "_build/install/default/lib/banana/basics/basics__Flow_graph.cmti" {"basics/basics__Flow_graph.cmti"}
  "_build/install/default/lib/banana/basics/basics__Flow_graph.cmx" {"basics/basics__Flow_graph.cmx"}
  "_build/install/default/lib/banana/basics/basics__Generate.cmi" {"basics/basics__Generate.cmi"}
  "_build/install/default/lib/banana/basics/basics__Generate.cmt" {"basics/basics__Generate.cmt"}
  "_build/install/default/lib/banana/basics/basics__Generate.cmx" {"basics/basics__Generate.cmx"}
  "_build/install/default/lib/banana/basics/basics__Linked_array.cmi" {"basics/basics__Linked_array.cmi"}
  "_build/install/default/lib/banana/basics/basics__Linked_array.cmt" {"basics/basics__Linked_array.cmt"}
  "_build/install/default/lib/banana/basics/basics__Linked_array.cmti" {"basics/basics__Linked_array.cmti"}
  "_build/install/default/lib/banana/basics/basics__Linked_array.cmx" {"basics/basics__Linked_array.cmx"}
  "_build/install/default/lib/banana/basics/display.ml" {"basics/display.ml"}
  "_build/install/default/lib/banana/basics/dynamic_array.ml" {"basics/dynamic_array.ml"}
  "_build/install/default/lib/banana/basics/dynamic_array.mli" {"basics/dynamic_array.mli"}
  "_build/install/default/lib/banana/basics/flow_graph.ml" {"basics/flow_graph.ml"}
  "_build/install/default/lib/banana/basics/flow_graph.mli" {"basics/flow_graph.mli"}
  "_build/install/default/lib/banana/basics/generate.ml" {"basics/generate.ml"}
  "_build/install/default/lib/banana/basics/linked_array.ml" {"basics/linked_array.ml"}
  "_build/install/default/lib/banana/basics/linked_array.mli" {"basics/linked_array.mli"}
  "_build/install/default/lib/banana/dune-package"
  "_build/install/default/lib/banana/opam"
]
libexec: [
  "_build/install/default/lib/banana/basics/basics.cmxs" {"basics/basics.cmxs"}
]
bin: [
  "_build/install/default/bin/main"
]
